spring:
  profiles:
    active: dev
  application:
    name: product-service
  config:
    import: optional:configserver:http://localhost:8888
server:
  port: 8082
mongock:
  change-logs-scan-package: com.micorservice.store.productservice.config